name: Python test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Lint
        run: |
          flake8 . --count --show-source --statistics --exclude=./test_*.py
      - name: output
        run: |
          pytest test_*.py –-junitxml=’テスト結果.xml’
      - name: Test
        run: |
          pytest test_*.py
